# Generated by Django 2.1.1 on 2018-12-23 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeamLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Visistor', max_length=120, null=True)),
                ('beam_length', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='BeamSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.CharField(max_length=120)),
                ('support_distance', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beamLength', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beam_support', to='beam_diagram.BeamLength')),
            ],
        ),
        migrations.CreateModel(
            name='PointLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_load', models.IntegerField()),
                ('point_load_distance', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beamLength', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='point_load', to='beam_diagram.BeamLength')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='beamlength',
            index_together={('id', 'user')},
        ),
    ]
