# Generated by Django 2.1.1 on 2018-12-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beam_diagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment_load', models.IntegerField()),
                ('moment_load_distance', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beamLength', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moment_load', to='beam_diagram.BeamLength')),
            ],
        ),
    ]
