# Generated by Django 2.1.1 on 2018-12-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beam_diagram', '0002_momentload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamsupport',
            name='support',
            field=models.CharField(choices=[('ROLLER_SUPPORT', 'roller_support'), ('PIN_SUPPORT', 'pin_support'), ('FIXED_SUPPORT', 'fixed_support')], default='PIN_SUPPORT', max_length=20),
        ),
    ]
