# Generated by Django 2.1.1 on 2018-12-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beam_diagram', '0006_auto_20181228_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamlength',
            name='beam_length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='beamsupport',
            name='support_distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='momentload',
            name='moment_load',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='momentload',
            name='moment_load_distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pointload',
            name='point_load',
            field=models.FloatField(),
        ),
    ]
