# Generated by Django 2.1.1 on 2018-12-30 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beam_diagram', '0007_auto_20181228_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributedLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_distributed_load', models.FloatField()),
                ('end_distributed_load', models.FloatField()),
                ('start_distributed_load_distance', models.FloatField()),
                ('end_distributed_load_distance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beamLength', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='distributed_load', to='beam_diagram.BeamLength')),
            ],
        ),
    ]
