# Generated by Django 2.1.1 on 2018-12-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beam_diagram', '0008_distributedload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributedload',
            old_name='end_distributed_load_distance',
            new_name='end_distributed_load_location',
        ),
        migrations.RenameField(
            model_name='distributedload',
            old_name='start_distributed_load_distance',
            new_name='start_distributed_load_location',
        ),
    ]
