# Generated by Django 2.1.1 on 2019-01-02 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beam_diagram', '0009_auto_20181230_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beamlength',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
